import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) 
	{
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		int children2 = 0 ; 
		int children3 = 0 ;
		int children4 = 0 ;
		int total = 0;


		for (int i = 0 ; i < T ; i++)
		{


			
			boolean girl = false ;
			boolean boy = false ; 
			int count = 0 ;


				while (girl==false || boy==false)
				{
					double a = generator.nextDouble();

						if (a<0.5)
						{	
							count++ ;
							boy = true;
							total++;
						}
									
						else 
						{
							count++;
							girl = true ;
							total++;
						}								
								
                  }
                  if (count==2)
						children2++;
					if (count==3)
							children3++;
					if (count>3)
							children4++;
														
		}
			double evrage = (double)total/T ;
			System.out.println("Average: " + evrage + " children to get at least one of each gender.");
			System.out.println("Number of families with 2 children: "+ children2);
			System.out.println("Number of families with 3 children: "+ children3);						
			System.out.println("Number of families with 4 or more children: "+ children4);
			if (children2>children3&&children2>children4)
			{
				System.out.println("The most common number of children is 2.");
			}
				else if (children3>children2&&children3>children4)
						System.out.println("The most common number of children is 3.");
					else if (children4>children2&&children4>children3)
							System.out.println("The most common number of children is 4.");
							
							

		}	    
}

